# Website Information
title : "FVHSsec"
description : "Fountain Valley High School Security Club"
url : "https://fvhssec.github.io"
baseurl : ""
permalink : "/:categories/:title"

# Author Information
author : "Baron"
  name : "FVHS"

email: "fvhssec@pm.me"
