# Website Information
title : "FVHS Cyber Security"
description: "Fountain Valley High School Cyber Security Club"
url: "https://fvhssec.github.io/"
baseurl: "/"
hosted_url: ""
permalink: /:categories/:title

# Author Information
email: "fvhssec@pm.me"

# Markdown Settings
markdown : kramdown