<<<<<<< HEAD
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title
relative_permalinks: true

# Setup
title:            "FVHSsec"
tagline:          'Cyber Security'
description:      'Fountain Valley High School Cyber Security'
url:              "http://hyde.getpoole.com"
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/FVHSsec/fvhssec.github.io
