# Website Information
title : "FVHSsec"
description : "Fountain Valley High School Security Club"
url : "https://fvhssec.github.io"
baseurl : "/"

cssurl : "/assets/css"
imageurl : "/assets/images"

docimageurl : "/assets/images/library/references"

permalink : "/:categories/:title"

# Collection Information
collections:
  references:
    output : true
    permalink : "/:categories/:title"
  
  
# Author Information
author :
  name : "FVHS"
  email: "fvhssec@pm.me"

#Social Network Service Information
github : "github.com/FVHSsec"
